spring:
  datasource:
    url: jdbc:mysql://localhost:3306/snow?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
              #?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20

mybatis:
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.jaytang.model
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations: classpath:mappings/*.xml


