spring:
  datasource:
    url: jdbc:mysql://localhost:3306/snow?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    #数据库引擎
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数（使用负值表示没有限制）
        max-active: 8
        #最大空闲连接
        max-idle: 8
        min-idle: 0
mybatis:
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.jaytang.model
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations: classpath:mappings/*.xml


#日志配置 具体配置在这个xml中
#日志级别从低到高分为TRACE < DEBUG < INFO < WARN < ERROR < FATAL，如果设置为WARN，则低于WARN的信息都不会输出。
logging:
  config: classpath:logback-spring.xml


